### ISSUE TITLE
Bolley fejlesztés TRA-ra - Our projects

### ISSUE THREAD

**Issue by SZPA-KTI** [SimonNagy/bolley#5]
**Our projects - új lapfül**
Benefits után jobbra. 

Electrification of bus lines, conversion diesel bus lines to an electric ones 
BKK, Budapest
*kép esetleg a hálózatról...

**Comment by SimonNagy** [comment]
v02 <= section-color-mod

**Comment by SimonNagy** [comment]
v02 <= our project
