### ISSUE TITLE
Bolley fejlesztés TRA-ra - Cikkek

### ISSUE THREAD

**Issue by SZPA-KTI** [SimonNagy/bolley#6]
A következő cikkeket kellene feltenni:

1. Legújabb legfelül:

Péter Ákos SZILASSY, Dávid FÖLDES PhD
Consumption estimation method for battery-electric buses using general line characteristics and temperature
https://www.sciencedirect.com/science/article/abs/pii/S0360544222019752

Scientific journal paper in the Energy journal (Volume 261, Part A, 15 December 2022)
IF: 8,85

2. 

Péter Ákos SZILASSY, Bence JENŐFI, Dávid FÖLDES PhD
Marginal energy consumption cost factors of battery electric buses
https://ieeexplore.ieee.org/document/9792553

Scientific conference paper in the Proceedings of the Smart City Symposium Prague (SCSP) 2022

**Comment by SimonNagy** [comment]
v02 <= update-papers
